### PR TITLE
Justin maximus theodore bernier thebaldus hamonet christopher thyripides lee

### PR DESCRIPTION
**Pull request by 810636**
food that teleports when it loses a lot of health
a flock that flocks to food and surrounds it while having a lot of health

### CODE REVIEW

**Comment by 810636** [comment]
flock that flocks around food and food that teleports when it loses a lot of health

**Review by 810218 — APPROVED** [review]
Looks good to me. Changes in main files are minor

**Review by 813002 — CHANGES_REQUESTED** [review]
Only 4 things are on screen. A random collection of lines that don't seem to do much besides change shape and size(might be meant as part system but isn't clear in branch name), 2 ship looking objects that do nothing besides appear on world canvas, and green particles, which I am assuming are meant to be food, which look like they work as intended by looking at code.

**Comment by 810218** [comment]
Justin your pull request looks—and I use this word sparingly—splendiferous

**Comment by sanjanksen** [comment]
Extrordinatory perfomance that is quite derogatory

**Pull request merged**
